version: '3.7'
services:
    web:
        build: './front/my-app/'
        image: ffelna-front
        container_name: ffelna-front
        # command: prod
        restart: always
        # stdin_open: true
        # tty: true
        # volumes:
        #   - ./front/my-app:/home/app
        ports:
            - 80:80
        networks:
            - some_net
        depends_on:
            - api
    api:
        build: ./ffelna-shop
        volumes:
            - ./images/:/images/
        ports:
            - 5000:8000
        environment:
            - DB_URI=postgresql://postgres:postgres@db/ffelna_shop
        depends_on:
            - admin
        networks:
            - some_net
    admin:
        build: ./ffelna-admin
        volumes:
            - ./images/:/images/
        ports:
            - 8000:8000
        environment:
            - DB_NAME=ffelna_shop
            - DB_USER=postgres
            - DB_PASSWORD=postgres
            - DB_HOST=db
            - DB_PORT=5432
        depends_on:
            - db
        networks:
            - some_net
    db:
        image: postgres:12.0-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=ffelna_shop
        networks:
            - some_net
volumes:
    postgres_data:
networks:
    some_net:
